### PR TITLE
Use GoogleTest for C++ tests (#289)

### PR DESCRIPTION
**Pull request by dalboris**
#289

### CODE REVIEW

**Comment by myin142** [comment]
Just a quick question. Is there a reason why you are not using a dependency manager? It would be much easier to manage dependencies that way, instead of copying all third party files into the source code.
A quick google search, I found a pretty good one: conan.io

**Comment by dalboris** [comment]
@myin142 No specific reasons, apart from the fact that they seem to solve a problem I never really encountered, and it would be one more tool to learn. I conceptually prefer to have everything needed to compile in the source tree. This way, I'm sure it doesn't change, and people just have to `git clone` and everything is there. So I just do this and it works. I would do it for Qt and Python if it wasn't several hundreds of MB and take forever to compile. ;-)

Dependency managers seem useful when you have dependencies which themselves have dependencies, some potentially shared, with conflicting versions, etc. I don't have that apart from the two behemoths Qt and Python, but those are typically readily available in build machines (Travis, Appveyor, etc.). So especially for things like pybind11, Eigen, and GoogleTest, which have zero dependencies themselves, and are quite lightweight, I don't see why no keeping them in the tree :)

**Comment by dalboris** [comment]
The error I got on Windows is documented here:

https://github.com/google/googletest/blob/master/googletest/README.md#visual-studio-dynamic-vs-static-runtimes

> Visual Studio Dynamic vs Static Runtimes
> By default, new Visual Studio projects link the C runtimes dynamically but Google Test links them statically. This will generate an error that looks something like the following: gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
> 
> Google Test already has a CMake option for this: gtest_force_shared_crt
> 
> Enabling this option will make gtest link the runtimes dynamically too, and match the project in which it is included.

Seems pretty straitghforward to fix.

**Comment by dalboris** [comment]
Interesting thread "[CMake] How the heck does one set options?" with actually `gtest_force_shared_crt` being the example:

https://cmake.org/pipermail/cmake/2011-November/047186.html

**Pull request merged**
